### ISSUE TITLE
Update LDP to fsa-style@2.5.3

### ISSUE THREAD

**Issue by francisrupert** [USDA-FSA/ldp#5]
[`2.5.3`](https://github.com/USDA-FSA/fsa-style/releases/tag/2.5.3) published, which includes the hotfix for https://github.com/USDA-FSA/fsa-style/issues/454

https://github.com/USDA-FSA/ldp/blob/07c06524f6d86082bb05584c561f5ee05676e3ba/package.json#L33

**Comment by bignamehere** [comment]
updated
